Revert "Provide alternate SE RoT provisioning path."
This reverts commit 47dc0c0ea3e82d451f295e7ba5c21188ecffaa13.

reason for revert: compilation error on pixel device

error.log by: h311hound

system/core/trusty/keymaster/include/trusty_keymaster/TrustyKeyMintDevice.h:84:7
4: error: only virtual member functions can be marked 'override'
    ScopedAStatus getRootOfTrustChallenge(array<uint8_t, 16>* challenge) overrid
e;
                                                                         ^~~~~
~
system/core/trusty/keymaster/include/trusty_keymaster/TrustyKeyMintDevice.h:86:6
4: error: only virtual member functions can be marked 'override'
                                 vector<uint8_t>* rootOfTrust) override;
                                                               ^~~~~~
system/core/trusty/keymaster/include/trusty_keymaster/TrustyKeyMintDevice.h:87:7
1: error: only virtual member functions can be marked 'override'
    ScopedAStatus sendRootOfTrust(const vector<uint8_t>& rootOfTrust) override;

probably needs some counterpart on [1]

[1]: https://android.googlesource.com/platform/system/keymaster/
Signed-off-by: minaripenguin <alexfinhart@gmail.com>